import type { Metadata } from "next";
import "./globals.css";
import "@/core/translation/i18n";
import { AccessibilityProvider } from "@/modules/components/AccessibilityProvider";
import InitLanguage from "@/modules/components/initLanguage";

export const metadata: Metadata = {
  title: "Bokk",
  description: "Generated by Bokk Digital Music",

  icons: {
    icon: [{ url: "/favicon.svg", type: "image/svg+xml" }],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"min-h-screen flex flex-col antialiased"}>
        <InitLanguage />
        <AccessibilityProvider>
          <main className="flex-1">{children}</main>
        </AccessibilityProvider>
      </body>
    </html>
  );
}
