import type { Metadata } from "next";
import "./globals.css";
import "@/core/translation/i18n";
import { AccessibilityProvider } from "@/modules/components/AccessibilityProvider";
import Header from "@/modules/layouts/header";
import Footer from "@/modules/layouts/footer";

export const metadata: Metadata = {
  title: "Disktro",
  description: "Generated by Disktro Digital Music",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"min-h-screen flex flex-col antialiased"}>
        <AccessibilityProvider>
          <main className="flex-1">{children}</main>
        </AccessibilityProvider>
      </body>
    </html>
  );
}
